    spring.application.name=hrms
    spring.data.mongodb.uri=mongodb+srv://hrmsuser:HrmsUser%40123@hrmscluster.bu8kvrz.mongodb.net/hrms?retryWrites=true&w=majority&appName=HRMSCluster
    spring.data.mongodb.database=hrms
    server.port=8080
